services:
  database:
    container_name: whispering-database
    env_file:
      - ../.env
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db-storage:/data/db
volumes:
  db-storage: